spring.application.name=ourlorien

#temporário - antes de usar flyway - dá permissão ao hibernate de criar tabelas
spring.jpa.hibernate.ddl-auto=create

## CONFIGURAÇÕES DOCKER.COMPOSE
spring.docker.compose.file=../compose.yaml
spring.docker.compose.skip.in-tests=false
#spring.docker.compose.enabled=false